@Host = http://localhost:5000
@SubscriptionId = 77b67776-3e88-4e70-888c-208ada4e5f8f

GET {{Host}}/api/Subscriptions/{{SubscriptionId}}
Accept: application/json



# {
#     "Id":{{AdminId}},
#     "subscriptionType": "Free",
# }
