@Host = http://localhost:5000
@SubscriptionId = 64d47601-73bb-4ce2-ad3e-3eebe969c027

GET {{Host}}/api/Subscriptions/{{SubscriptionId}}
Accept: application/json


# {
#     "Id":{{AdminId}},
#     "subscriptionType": "Free",
# }
