@host = http://localhost:5000
@subscriptionId = ec065da7-c01a-4618-ab65-98386860f10a

GET {{host}}/api/Subscriptions/{{subscriptionId}}
Accept: application/json


# {
#     "Id":{{AdminId}},
#     "subscriptionType": "Free",
# }
