@host=http://localhost:5000
@subscriptionId= ec065da7-c01a-4618-ab65-98386860f10a
POST {{host}}/api/subscriptions/{{subscriptionId}}/gyms
Content-Type: application/json

{
    "Name": "sss's gym"
}

###